// Macros for different fuji models

#define FUJI_X_T20

#ifdef FUJI_X_A2
	#define FUJI_IMAGE_GET_VERSION 1
	#define FUJI_IMAGE_EXPLORE_VERSION 2
	#define FUJI_REMOTE_VERSION 0x0
	#define FUJI_START_CAM_STATE FUJI_FULL_ACCESS
#endif

#ifdef FUJI_X_T20
	#define FUJI_USE_REMOTE_MODE

	#define FUJI_IMAGE_GET_VERSION 3
	#define FUJI_IMAGE_EXPLORE_VERSION 4
	#define FUJI_REMOTE_VERSION 0x00020004
	#define FUJI_REMOTE_IMAGE_EXPLORE_VERSION 2

	#define FUJI_START_CAM_STATE FUJI_REMOTE_ACCESS
#endif

#ifdef FUJI_X_S10
	#define FUJI_USE_REMOTE_MODE

	#define FUJI_IMAGE_GET_VERSION 3
	#define FUJI_IMAGE_EXPLORE_VERSION 5
	#define FUJI_REMOTE_VERSION 0x00020004
	#define FUJI_REMOTE_IMAGE_EXPLORE_VERSION 4

	#define FUJI_START_CAM_STATE FUJI_REMOTE_ACCESS
#endif
